# Generated by Django 5.0.6 on 2024-08-29 03:47
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.ImageField(default=timezone.now),
        ),
    ]
